
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  paths-to-match:
    - /api/**

# JPA
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}

#Multipart
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
